trigger:
- main

pool:
  name: devLinux
  demands:
    - agent.name -equals myAgent

variables:
  - group: "Dev"

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    # Install .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    # Restore dependencies
    - script: dotnet restore
      displayName: 'Restore Dependencies'

    # Build the project
    - script: dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Build Project'

    # Run unit tests
    - script: dotnet test
      displayName: 'Run Unit Tests'

    # List build output
    - script: ls -R $(Build.ArtifactStagingDirectory)
      displayName: 'List Build Output'

    # Publish the build output
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    # Download the build artifact
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    # List downloaded artifact contents
    - script: ls -R $(Pipeline.Workspace)/drop
      displayName: 'List Downloaded Artifact'

    # Login to Azure
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'devWebApp2025'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
          az account set --subscription $(subscription_id)

    - task: CmdLine@2
      inputs:
        script: |
          echo "Installing zip utility..."
          sudo apt-get update
          sudo apt-get install -y zip
          echo "Zip utility installed."

          echo "Creating zip file..."
          zip -r /home/azureuser/myagent/_work/2/drop/MySampleApp.zip /home/azureuser/myagent/_work/2/drop/*
          echo "Zip file created."

    - task: CmdLine@2
      inputs:
        script: |
          echo "Listing contents of the directory..."
          ls -R /home/azureuser/myagent/_work/2/drop

    - task: AzureRmWebAppDeployment@4
      inputs:
        azureSubscription: 'devWebApp2025'
        appType: 'webApp' # Use 'webApp' if Windows-based
        WebAppName: 'devWebApp2025'
        packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
        # Remove RuntimeStack and StartupCommand if not required