trigger:
- main # Trigger on changes to the 'main' branch in GitHub

pool:
  name: devLinux
  demands:
    - agent.name -equals myAgent

variables:
  - group: "Dev"
  - name: NUGET_FEED_URL
    value: "https://pkgs.dev.azure.com/StanislavKostenich0849/azuredevopsproject/_packaging/MyDependenciesFeed/nuget/v3/index.json"
  - name: NUGET_FEED_NAME
    value: "MyDependenciesFeed"

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    # Checkout code from GitHub
    - checkout: self # This clones the GitHub repository
      clean: true # Optional: Cleans the repository before cloning

    # Install .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    # Restore dependencies from Azure Artifacts feed
    - script: |
        dotnet nuget add source $(NUGET_FEED_URL) --name $(NUGET_FEED_NAME) --username "az" --password "$(System.AccessToken)" --store-password-in-clear-text
        dotnet restore
      displayName: 'Restore Dependencies from Azure Artifacts'

    # Build the project
    - script: dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Build Project'

    # Run unit tests
    - script: dotnet test
      displayName: 'Run Unit Tests'

    # Publish NuGet packages to Azure Artifacts feed
    - script: |
        dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)/nuget
        dotnet nuget push $(Build.ArtifactStagingDirectory)/nuget/*.nupkg --source $(NUGET_FEED_URL) --api-key az
      displayName: 'Publish NuGet Packages to Azure Artifacts'

    # List build output
    - script: ls -R $(Build.ArtifactStagingDirectory)
      displayName: 'List Build Output'

    # Publish the build output
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    # Download the build artifact
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    # List downloaded artifact contents
    - script: ls -R $(Pipeline.Workspace)/drop
      displayName: 'List Downloaded Artifact'

    # Login to Azure
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'devWebApp2025'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
          az account set --subscription $(subscription_id)

    # Install zip utility and create zip file
    - task: CmdLine@2
      inputs:
        script: |
          echo "Installing zip utility..."
          sudo apt-get update
          sudo apt-get install -y zip
          echo "Zip utility installed."

          echo "Creating zip file..."
          zip -r $(Pipeline.Workspace)/drop/MySampleApp.zip $(Pipeline.Workspace)/drop/*
          echo "Zip file created."

    # List contents of the directory
    - task: CmdLine@2
      inputs:
        script: |
          echo "Listing contents of the directory..."
          ls -R $(Pipeline.Workspace)/drop

    # Deploy to Azure Web App
    - task: AzureRmWebAppDeployment@4
      inputs:
        azureSubscription: 'devWebApp2025'
        appType: 'webApp' # Use 'webApp' if Windows-based
        WebAppName: 'devWebApp2025'
        packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'